package loom_test

import (
	"context"
	"fmt"
	"testing"

	"github.com/jinyitao123/loom"
)

func TestGraph_SingleStep(t *testing.T) {
	g := loom.NewGraph("test", "only_step")
	g.AddStep("only_step", echoStep("output", "hello"), loom.End())

	result, err := g.Run(context.Background(), loom.State{}, nil)
	assertNoError(t, err)
	assertState(t, result, "output", "hello")
	assertSteps(t, result, 1)
}

func TestGraph_LinearChain(t *testing.T) {
	cfg := loom.DefaultMergeConfig()
	cfg.Register("trace", loom.AppendSlice)
	g := loom.NewGraph("test", "a", loom.WithMergeConfig(cfg))
	g.AddStep("a", collectStep("a"), loom.Always("b"))
	g.AddStep("b", collectStep("b"), loom.Always("c"))
	g.AddStep("c", collectStep("c"), loom.End())

	result, err := g.Run(context.Background(), loom.State{}, nil)
	assertNoError(t, err)
	assertTrace(t, result, "a", "b", "c")
	assertSteps(t, result, 3)
}

func TestGraph_ConditionalBranching(t *testing.T) {
	g := loom.NewGraph("test", "check")
	g.AddStep("check", echoStep("status", "pass"), loom.Branch("status", map[string]string{
		"pass": "success",
		"fail": "error",
	}, "error"))
	g.AddStep("success", echoStep("result", "ok"), loom.End())
	g.AddStep("error", echoStep("result", "failed"), loom.End())

	result, err := g.Run(context.Background(), loom.State{}, nil)
	assertNoError(t, err)
	assertState(t, result, "result", "ok")
	assertLastStep(t, result, "success")
}

func TestGraph_Loop_WithExit(t *testing.T) {
	g := loom.NewGraph("test", "inc")
	g.AddStep("inc", counterStep("n"), loom.Condition(
		func(s loom.State) bool { n, _ := s["n"].(int); return n >= 3 },
		"",    // halt when n >= 3
		"inc", // loop back
	))

	result, err := g.Run(context.Background(), loom.State{"n": 0}, nil)
	assertNoError(t, err)
	assertState(t, result, "n", 3)
	assertSteps(t, result, 3)
}

func TestGraph_MaxIter_Breaker(t *testing.T) {
	g := loom.NewGraph("test", "loop", loom.WithMaxIterations(5))
	g.AddStep("loop", counterStep("n"), loom.Always("loop"))

	_, err := g.Run(context.Background(), loom.State{}, nil)
	assertError(t, err, "exceeded max iterations")
}

func TestGraph_StepNotFound(t *testing.T) {
	g := loom.NewGraph("test", "nonexistent")
	_, err := g.Run(context.Background(), loom.State{}, nil)
	assertError(t, err, "step \"nonexistent\" not found")
}

func TestGraph_StepError_AbortsGraph(t *testing.T) {
	g := loom.NewGraph("test", "a")
	g.AddStep("a", echoStep("ok", "1"), loom.Always("b"))
	g.AddStep("b", failStep("something broke"), loom.Always("c"))
	g.AddStep("c", echoStep("unreachable", "true"), loom.End())

	result, err := g.Run(context.Background(), loom.State{}, nil)
	assertError(t, err, "something broke")
	assertState(t, result, "__error", "something broke")
	assertState(t, result, "__failed_step", "b")
	if result.State["unreachable"] != nil {
		t.Error("step c should not have executed")
	}
}

func TestGraph_RunID_AutoGenerated(t *testing.T) {
	g := loom.NewGraph("test", "s")
	g.AddStep("s", echoStep("x", "1"), loom.End())

	result, _ := g.Run(context.Background(), loom.State{}, nil)
	if result.RunID == "" {
		t.Error("RunID should be auto-generated")
	}
}

func TestGraph_RunID_SafeNonString(t *testing.T) {
	g := loom.NewGraph("test", "s")
	g.AddStep("s", echoStep("x", "1"), loom.End())

	result, err := g.Run(context.Background(), loom.State{"__run_id": 12345}, nil)
	assertNoError(t, err)
	if result.RunID == "" {
		t.Error("RunID should be generated despite bad input")
	}
}

func TestGraph_Checkpoint_Saved(t *testing.T) {
	store := loom.NewMemStore()
	g := loom.NewGraph("myagent", "s")
	g.AddStep("s", echoStep("x", "1"), loom.End())

	result, _ := g.Run(context.Background(), loom.State{}, store)

	data, err := store.Get(context.Background(), "checkpoint:myagent", result.RunID)
	assertNoError(t, err)
	if len(data) == 0 {
		t.Error("checkpoint data is empty")
	}
}

func TestGraph_Checkpoint_Required_FailAborts(t *testing.T) {
	store := &failingStore{Store: loom.NewMemStore(), failOn: "Put"}
	g := loom.NewGraph("test", "s", loom.WithCheckpointPolicy(loom.CheckpointRequired))
	g.AddStep("s", echoStep("x", "1"), loom.End())

	_, err := g.Run(context.Background(), loom.State{}, store)
	assertError(t, err, "checkpoint failed")
}

func TestGraph_Checkpoint_BestEffort_Continues(t *testing.T) {
	store := &failingStore{Store: loom.NewMemStore(), failOn: "Put"}
	g := loom.NewGraph("test", "s", loom.WithCheckpointPolicy(loom.CheckpointBestEffort))
	g.AddStep("s", echoStep("x", "1"), loom.End())

	result, err := g.Run(context.Background(), loom.State{}, store)
	assertNoError(t, err)
	assertState(t, result, "x", "1")
}

func TestGraph_Checkpoint_NilStore(t *testing.T) {
	g := loom.NewGraph("test", "s")
	g.AddStep("s", echoStep("x", "1"), loom.End())

	result, err := g.Run(context.Background(), loom.State{}, nil)
	assertNoError(t, err)
	assertState(t, result, "x", "1")
}

func TestGraph_RouterError_ReportsCorrectStep(t *testing.T) {
	g := loom.NewGraph("test", "a")
	g.AddStep("a", echoStep("x", "1"), func(_ context.Context, _ loom.State) (string, error) {
		return "", fmt.Errorf("router broke")
	})

	result, err := g.Run(context.Background(), loom.State{}, nil)
	assertError(t, err, "router broke")
	assertLastStep(t, result, "a")
}

func TestGraph_ContextCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	g := loom.NewGraph("test", "s")
	g.AddStep("s", func(ctx context.Context, _ loom.State) (loom.State, error) {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		default:
			return loom.State{"x": "1"}, nil
		}
	}, loom.End())

	_, err := g.Run(ctx, loom.State{}, nil)
	if err == nil {
		t.Error("expected context cancellation error")
	}
}

func TestGraph_StepBudget_ExhaustedAcrossSubgraphs(t *testing.T) {
	store := loom.NewMemStore()

	child := loom.NewGraph("child", "loop")
	child.AddStep("loop", counterStep("n"), loom.Always("loop"))

	parent := loom.NewGraph("parent", "run_child",
		loom.WithStepBudget(10),
		loom.WithMaxIterations(100),
	)
	parent.AddStep("run_child", func(ctx context.Context, state loom.State) (loom.State, error) {
		result, err := child.Run(ctx, state, store)
		if err != nil {
			return nil, err
		}
		return result.State, nil
	}, loom.End())

	_, err := parent.Run(context.Background(), loom.State{}, store)
	assertError(t, err, "step budget exhausted")
}

func TestGraph_MergeConfig_UsedInRun(t *testing.T) {
	cfg := loom.NewMergeConfig()
	cfg.Register("total", loom.SumInt)

	g := loom.NewGraph("test", "a", loom.WithMergeConfig(cfg))
	g.AddStep("a", func(_ context.Context, _ loom.State) (loom.State, error) {
		return loom.State{"total": 10}, nil
	}, loom.Always("b"))
	g.AddStep("b", func(_ context.Context, _ loom.State) (loom.State, error) {
		return loom.State{"total": 20}, nil
	}, loom.End())

	result, _ := g.Run(context.Background(), loom.State{"total": 5}, nil)
	assertState(t, result, "total", 35)
}
